### ISSUE TITLE
Create automation playbook for Squid deployment and configuration on Azure

### ISSUE THREAD

**Issue by dtollaku** [filetrust/mvp-icap-squid-cache-proxy#13]

**Comment by NourEddineX** [comment]
cadc9af6caf8f7c54752e3e37598094e261ccfb9

**Comment by NourEddineX** [comment]
I got a mail from GitGuardian regarding an exposed private key, It's totally fine, it's a demo private key for testing

**Comment by NadHodeGW** [comment]
Issues found while through & use the Read me documentation to test usage of playbook:
 1--Unable to use WSl to "run curl -L https://aka.ms/InstallAzureCli | bash # Install az"
 2--Using pip3 install --user ansible[azure] does not install ansible
 3--Executing the command: ansible-playbook -i <path to your ssh private key> azure-squid.yaml returns errors

QA Validation failed

**Comment by NadHodeGW** [comment]
Retested 
Playbook created successfully.
Some warning received:

WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
These two warnings should be ignored since we only use localhost for azure access and the newly created vm ip address which is dynamically added by the playbook itself after creating the vm on azure
[WARNING]: Updating cache and auto-installing missing dependency: python-apt
This warning is mentioning that python-apt is not installed so ansible can make use of it
It's fine because ansible is auto-installing it
--To be fixed in next push to allow ansible to use python3 instead (since python2 is now deprecated)
[WARNING]: Module did not set no_log for ssh_password_enabled
Should be fixed in the next push
