### ISSUE TITLE
Update the c-icap repo build-and-release.yml to deploy the built container to an Azure Container Registry within the Glasswall-ICAP subscription.

### ISSUE THREAD

**Issue by dtollaku** [filetrust/mvp-icap-squid-cache-proxy#8]

**Comment by IslamHeggy** [comment]
Edited the yaml file as well as adding the evaluation SDK as a submodule

**Comment by NadHodeGW** [comment]
This work has been validated by 

A new code merged to the master triggers a new image built and pushed to the Azure registry using Github actions & the new image is then deployed to a container instance.

The endpoint will need to be used successfully before this issue is closed (@NourEddineX  to help with this.)
